//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesForHands.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.MaterialSupplier = new HashSet<MaterialSupplier>();
        }
    
        public int IdMaterial { get; set; }
        public string NameMaterial { get; set; }
        public int IdTypeMaterial { get; set; }
        public string ImagePath { get; set; }
        public decimal Price { get; set; }
        public int Count { get; set; }
        public int MinCount { get; set; }
        public int CountInBox { get; set; }
        public int IdUnit { get; set; }
        public string GetImage
        {
            get
            {
                if (ImagePath != null)
                {
                    return $@"/Photo{ImagePath}";
                }
                else
                {
                    return ImagePath;
                }
            }
        }

        public virtual TypeMaterial TypeMaterial { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialSupplier> MaterialSupplier { get; set; }
    }
}
